version: '3.4'

services:
  psqldb:
    image: postgres:10.13
    container_name: psqldb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - psqldb
  pricesynchronizer:
    image: pricesynchronizer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - psqldb
    networks:
      - psqldb

networks:
  psqldb:
    driver: bridge